### ISSUE TITLE
Connect to port different from 21

### ISSUE THREAD

**Issue by wizard699** [lloydsargent/BlackRaccoon#46]
How to connect to port 2000?

**Comment by fvvliet** [comment]
It's a pity this issue is closed without implementing, I need it too...

Frank

**Comment by lloydsargent** [comment]
Black Raccoon works with the FTP routines as provided by Apple. This was closed because there is no obvious method that allows you to specify the port.

It isn’t a question of me implementing it, it is a question of Apple implementing it (and they have many times said they planned on deprecating the FTP routines).

If you find a way to specify the port, I would be happy to implement it.

**Comment by fvvliet** [comment]
Ok thank you for the explanation.

Frank

**Comment by brunodeandrade** [comment]
Any news regarding this question? Nothing? I really needed this..

**Comment by lloydsargent** [comment]
There is no method that I’m aware of that allows you to specify the port. Feel free to notify me if you find one.
