### ISSUE TITLE
Background download is not working!!

### ISSUE THREAD

**Issue by hadwanihardik** [lloydsargent/BlackRaccoon#53]
Download works fine, but if i make app in background.. download stops.
Is there any provision for background downloading?

**Comment by lloydsargent** [comment]
BR was designed to use Apples routines. Since I was unable to determine if they were thread safe, they run on the main thread. 

If you did things correctly, the download should not affect your GUI response. The sample project shows how it is designed to work. 

There are projects which have done FTP from scratch which may allow background threads.  Unfortunately, other than knowing they exist, I can't help you with them. 

Cheers,

Lloyd

**Comment by hadwanihardik** [comment]
Hello lloyd,
Thanks for kind reply.
I am asking about background mode of app.
Means can this code changed to work even if app is not in forground of
iphone?

**Comment by lloydsargent** [comment]
My honest answer is I don't know. I've not attempted it but am guessing (this is only a guess) that Apple prevents it. BR calls Apple routines which, at best, are poorly documented. 

If your tests show that it doesn't work, then I suspect Apple suspends FTP when in background to conserve battery power. Unfortunately this is only a guess. 

I wish I could be more definitive. I derive a lot of the information from the same sources you do (Apple doesn't take my calls :) as well as many hours of testing ... And yes, it can be very frustrating. Esp. when code acts differently across multiple versions of iOS. 

If you figure out how to get it to work I would love to know. 

Sorry I'm not able to help more,

Lloyd
